import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
  },
  password: {
    type: String,
    required: true,
  },
  userData: {
    products: {
      type: Array,
      default: [
        {
          id: 1,
          title: "Овочі, 🍅 🥒",
          proteins: 3,
          fats: 0,
          carbohydrates: 7,
          calories: 47,
          isFavorite: true,
        },
        {
          id: 2,
          title: "Яблуко, 🍌 фрукти, ягоди",
          proteins: 1,
          fats: 0.2,
          carbohydrates: 16,
          calories: 63,
          isFavorite: true,
        },
        {
          id: 3,
          title: "Вівсянка",
          proteins: 11,
          fats: 6,
          carbohydrates: 48,
          calories: 303,
          isFavorite: true,
        },
        {
          id: 4,
          title: "Гриби",
          proteins: 3,
          fats: 1.5,
          carbohydrates: 0,
          calories: 25,
          isFavorite: false,
        },
        {
          id: 5,
          title: "Кукурудза варена",
          proteins: 4,
          fats: 2,
          carbohydrates: 23,
          calories: 123,
          isFavorite: false,
        },
        {
          id: 6,
          title: "Авокадо",
          proteins: 2,
          fats: 20,
          carbohydrates: 7.4,
          calories: 208,
          isFavorite: false,
        },
        {
          id: 7,
          title: "Морква по-корейськи",
          proteins: 1.2,
          fats: 6.6,
          carbohydrates: 9.6,
          calories: 122,
          isFavorite: true,
        },
        {
          id: 8,
          title: "Апельсин / мандарин",
          proteins: 1,
          fats: 0,
          carbohydrates: 8,
          calories: 36,
          isFavorite: false,
        },
        {
          id: 9,
          title: "Банани",
          proteins: 2,
          fats: 0,
          carbohydrates: 22,
          calories: 95,
          isFavorite: false,
        },
        {
          id: 10,
          title: "Кавун або диня",
          proteins: 1,
          fats: 0,
          carbohydrates: 8,
          calories: 33,
          isFavorite: false,
        },
        {
          id: 11,
          title: "Яєчний білок (1шт-35г)",
          proteins: 11.1,
          fats: 1,
          carbohydrates: 0.7,
          calories: 48,
          isFavorite: true,
        },
        {
          id: 12,
          title: "Яйце з жовт (1шт-50г)",
          proteins: 12.3,
          fats: 11,
          carbohydrates: 0.9,
          calories: 160,
          isFavorite: true,
        },
        {
          id: 13,
          title: "Сир нежирний",
          proteins: 18,
          fats: 1.8,
          carbohydrates: 0.7,
          calories: 88,
          isFavorite: false,
        },
        {
          id: 14,
          title: "Сир домашній 18%",
          proteins: 14,
          fats: 18,
          carbohydrates: 2.8,
          calories: 232,
          isFavorite: false,
        },
        {
          id: 15,
          title: "Сметана 15%",
          proteins: 2,
          fats: 15,
          carbohydrates: 3,
          calories: 160,
          isFavorite: false,
        },
        {
          id: 16,
          title: "Сметана 20%",
          proteins: 2.6,
          fats: 20,
          carbohydrates: 3,
          calories: 202,
          isFavorite: false,
        },
        {
          id: 17,
          title: "Сир",
          proteins: 24,
          fats: 30,
          carbohydrates: 1,
          calories: 363,
          isFavorite: false,
        },
        {
          id: 18,
          title: "Путасу",
          proteins: 16.1,
          fats: 0.9,
          carbohydrates: 0,
          calories: 72,
          isFavorite: false,
        },
        {
          id: 19,
          title: "Хек, минтай, камбала сира",
          proteins: 16.5,
          fats: 1.8,
          carbohydrates: 0,
          calories: 82,
          isFavorite: false,
        },
        {
          id: 20,
          title: "Тунець сирий",
          proteins: 23,
          fats: 1,
          carbohydrates: 0,
          calories: 101,
          isFavorite: false,
        },
        {
          id: 21,
          title: "Кижуч, горбуша сира",
          proteins: 21,
          fats: 6,
          carbohydrates: 0,
          calories: 140,
          isFavorite: false,
        },
        {
          id: 22,
          title: "Оселедець солоний",
          proteins: 19.8,
          fats: 15.4,
          carbohydrates: 0,
          calories: 217,
          isFavorite: false,
        },
        {
          id: 23,
          title: "Сьомга",
          proteins: 25,
          fats: 24,
          carbohydrates: 0,
          calories: 310,
          isFavorite: false,
        },
        {
          id: 24,
          title: "Скумбрія солона",
          proteins: 19,
          fats: 25,
          carbohydrates: 0,
          calories: 305,
          isFavorite: false,
        },
        {
          id: 25,
          title: "Міді",
          proteins: 14,
          fats: 2.2,
          carbohydrates: 1.2,
          calories: 91,
          isFavorite: false,
        },
        {
          id: 26,
          title: "Кальмари відварені",
          proteins: 21.2,
          fats: 2.8,
          carbohydrates: 2,
          calories: 122,
          isFavorite: false,
        },
        {
          id: 27,
          title: "Морський коктейль",
          proteins: 14.7,
          fats: 3,
          carbohydrates: 1.25,
          calories: 124,
          isFavorite: false,
        },
        {
          id: 28,
          title: "Курка / індичка в дух",
          proteins: 16,
          fats: 11,
          carbohydrates: 0,
          calories: 168,
          isFavorite: false,
        },
        {
          id: 29,
          title: "Куряча грудка сира",
          proteins: 24,
          fats: 2,
          carbohydrates: 0,
          calories: 113,
          isFavorite: false,
        },
        {
          id: 30,
          title: "Індичка сира",
          proteins: 20,
          fats: 3,
          carbohydrates: 0,
          calories: 130,
          isFavorite: false,
        },
        {
          id: 31,
          title: "Свинина сира",
          proteins: 17,
          fats: 16,
          carbohydrates: 1,
          calories: 218,
          isFavorite: false,
        },
        {
          id: 32,
          title: "Холодець із курки",
          proteins: 15,
          fats: 1,
          carbohydrates: 4,
          calories: 100,
          isFavorite: false,
        },
        {
          id: 33,
          title: "Протеїн (1 скуп - 20г)",
          proteins: 78,
          fats: 7,
          carbohydrates: 2.8,
          calories: 413,
          isFavorite: false,
        },
        {
          id: 34,
          title: "Кефір 2,5%",
          proteins: 3,
          fats: 4.2,
          carbohydrates: 2.5,
          calories: 52,
          isFavorite: false,
        },
        {
          id: 35,
          title: "Молоко",
          proteins: 3,
          fats: 4,
          carbohydrates: 5,
          calories: 62,
          isFavorite: false,
        },
        {
          id: 36,
          title: "Сирники",
          proteins: 16,
          fats: 8.2,
          carbohydrates: 18.2,
          calories: 210,
          isFavorite: false,
        },
        {
          id: 37,
          title: "Запіканка",
          proteins: 14.7,
          fats: 14,
          carbohydrates: 7.3,
          calories: 195,
          isFavorite: false,
        },
        {
          id: 38,
          title: "Адигейський / бринза",
          proteins: 18.5,
          fats: 18,
          carbohydrates: 0,
          calories: 260,
          isFavorite: false,
        },
        {
          id: 39,
          title: "Вершковий сир",
          proteins: 10.5,
          fats: 21.5,
          carbohydrates: 6,
          calories: 260,
          isFavorite: false,
        },
        {
          id: 40,
          title: "Яловичина",
          proteins: 26,
          fats: 17,
          carbohydrates: 0,
          calories: 254,
          isFavorite: false,
        },
        {
          id: 41,
          title: "Тунець жб",
          proteins: 14.3,
          fats: 13,
          carbohydrates: 0,
          calories: 177,
          isFavorite: false,
        },
        {
          id: 42,
          title: "Перець фарширований",
          proteins: 4,
          fats: 12,
          carbohydrates: 9,
          calories: 167,
          isFavorite: false,
        },
        {
          id: 43,
          title: "Сочевичний суп",
          proteins: 2.3,
          fats: 3,
          carbohydrates: 5.6,
          calories: 60,
          isFavorite: false,
        },
        {
          id: 44,
          title: "Картопля варена",
          proteins: 2.1,
          fats: 2.4,
          carbohydrates: 17,
          calories: 89,
          isFavorite: false,
        },
        {
          id: 45,
          title: "Квасоля",
          proteins: 9,
          fats: 5,
          carbohydrates: 24,
          calories: 94,
          isFavorite: false,
        },
        {
          id: 46,
          title: "Вівсянка Сквірянка",
          proteins: 11,
          fats: 5,
          carbohydrates: 65,
          calories: 345,
          isFavorite: false,
        },
        {
          id: 47,
          title: "Квашена капуста / огірки",
          proteins: 1.5,
          fats: 0.4,
          carbohydrates: 4,
          calories: 19,
          isFavorite: false,
        },
        {
          id: 48,
          title: "Гречка сира",
          proteins: 12.6,
          fats: 3,
          carbohydrates: 67.5,
          calories: 335,
          isFavorite: false,
        },
        {
          id: 49,
          title: "Гречка варена",
          proteins: 4.6,
          fats: 2.1,
          carbohydrates: 23,
          calories: 115,
          isFavorite: false,
        },
        {
          id: 50,
          title: "Макарони сирі",
          proteins: 12.5,
          fats: 1.3,
          carbohydrates: 73,
          calories: 360,
          isFavorite: false,
        },
        {
          id: 51,
          title: "Макарони відварені",
          proteins: 4.9,
          fats: 0.5,
          carbohydrates: 28,
          calories: 140,
          isFavorite: false,
        },
        {
          id: 52,
          title: "Картопля смажена",
          proteins: 2.8,
          fats: 9.5,
          carbohydrates: 24,
          calories: 192,
          isFavorite: false,
        },
        {
          id: 53,
          title: "Перловка відварена",
          proteins: 2.9,
          fats: 0.5,
          carbohydrates: 31,
          calories: 130,
          isFavorite: false,
        },
        {
          id: 54,
          title: "Млинці",
          proteins: 5,
          fats: 7,
          carbohydrates: 22,
          calories: 170,
          isFavorite: false,
        },
        {
          id: 55,
          title: "Кетчуп",
          proteins: 1,
          fats: 0,
          carbohydrates: 29,
          calories: 118,
          isFavorite: false,
        },
        {
          id: 56,
          title: "Рис",
          proteins: 7.1,
          fats: 0.7,
          carbohydrates: 78,
          calories: 365,
          isFavorite: false,
        },
        {
          id: 57,
          title: "Сочевиця, нут",
          proteins: 24,
          fats: 2,
          carbohydrates: 54,
          calories: 325,
          isFavorite: false,
        },
        {
          id: 58,
          title: "Хлібці / лаваш",
          proteins: 8.5,
          fats: 1.6,
          carbohydrates: 64.1,
          calories: 289,
          isFavorite: false,
        },
        {
          id: 59,
          title: "Окрошка",
          proteins: 3.7,
          fats: 7,
          carbohydrates: 4,
          calories: 90,
          isFavorite: false,
        },
        {
          id: 60,
          title: "Мед",
          proteins: 1,
          fats: 0,
          carbohydrates: 82,
          calories: 329,
          isFavorite: false,
        },
        {
          id: 61,
          title: "Масло вершкове",
          proteins: 0.5,
          fats: 82.5,
          carbohydrates: 0.8,
          calories: 748,
          isFavorite: false,
        },
        {
          id: 62,
          title: "Сало",
          proteins: 2.4,
          fats: 89,
          carbohydrates: 0,
          calories: 797,
          isFavorite: false,
        },
        {
          id: 63,
          title: "Сухофрукти, родзинки",
          proteins: 2.5,
          fats: 0.1,
          carbohydrates: 59,
          calories: 250,
          isFavorite: false,
        },
        {
          id: 64,
          title: "Грецькі горіхи",
          proteins: 15.2,
          fats: 65.2,
          carbohydrates: 7,
          calories: 654,
          isFavorite: false,
        },
        {
          id: 65,
          title: "Арахіс смажений",
          proteins: 27,
          fats: 47,
          carbohydrates: 10,
          calories: 620,
          isFavorite: false,
        },
        {
          id: 66,
          title: "Абрикоси сушені",
          proteins: 5,
          fats: 1,
          carbohydrates: 66,
          calories: 285,
          isFavorite: false,
        },
        {
          id: 67,
          title: "Чорнослив",
          proteins: 2.3,
          fats: 1,
          carbohydrates: 58,
          calories: 231,
          isFavorite: false,
        },
        {
          id: 68,
          title: "Фініки, інжир",
          proteins: 3,
          fats: 1,
          carbohydrates: 70,
          calories: 274,
          isFavorite: false,
        },
        {
          id: 69,
          title: "Зефір",
          proteins: 0.8,
          fats: 0,
          carbohydrates: 78.5,
          calories: 304,
          isFavorite: false,
        },
        {
          id: 70,
          title: "Печиво, сухарі",
          proteins: 6.5,
          fats: 14.4,
          carbohydrates: 71.8,
          calories: 437,
          isFavorite: false,
        },
        {
          id: 71,
          title: "Снікерс",
          proteins: 9.3,
          fats: 27.9,
          carbohydrates: 54.6,
          calories: 507,
          isFavorite: false,
        },
        {
          id: 72,
          title: "Казинаки",
          proteins: 14.8,
          fats: 42.6,
          carbohydrates: 34.5,
          calories: 576,
          isFavorite: false,
        },
        {
          id: 73,
          title: "Арахісова паста",
          proteins: 25,
          fats: 44,
          carbohydrates: 10,
          calories: 588,
          isFavorite: false,
        },
        {
          id: 74,
          title: "Олія Олейна",
          proteins: 0,
          fats: 99,
          carbohydrates: 0,
          calories: 900,
          isFavorite: false,
        },
      ],
    },
    meals: {
      type: Array,
      default: [],
    },
    weight: {
      type: Number,
      default: 75,
    },
  },
});

export default mongoose.model("User", userSchema);
